### ISSUE TITLE
Failed to resolve dependency

### ISSUE THREAD

**Issue by arshcaptano** [hajiyevelnur92/intentanimation#1]
Android studio fails to add this to my project. Shows this error:

Failed to resolve: com.github.hajiyevelnur92:intentanimation:1.0
Show in File
Show in Project Structure dialog

This is how I added it:
dependencies {
  ...
implementation 'com.github.hajiyevelnur92:intentanimation:1.0'
}

I also added the maven repository like this:
 repositories {
  ...
  maven { url 'https://jitpack.io' }
 }

Any help in resolving this will be appreciated.

**Comment by hajiyevelnur92** [comment]
please add maven under the allrepository hierarchy
